const students = [
  {
    id: 1,
    profilePhoto: "https://i.pravatar.cc/150?img=1",
    studentName: "Rahul Sharma",
    studentId: "STU001",
    department: "Computer Science",
    course: "BCA",
    email: "rahul@example.com",
    phoneNumber: "9876543210",
    address: "Pune",
    status: "Active",
  },
  {
    id: 2,
    profilePhoto: "https://i.pravatar.cc/150?img=2",
    studentName: "Priya Verma",
    studentId: "STU002",
    department: "Information Technology",
    course: "BSc IT",
    email: "priya@example.com",
    phoneNumber: "9876543211",
    address: "Mumbai",
    status: "Active",
  },
  {
    id: 3,
    profilePhoto: "https://i.pravatar.cc/150?img=3",
    studentName: "Amit Patil",
    studentId: "STU003",
    department: "Electronics",
    course: "BTech",
    email: "amit@example.com",
    phoneNumber: "9876543212",
    address: "Kolhapur",
    status: "Inactive",
  },
  {
    id: 4,
    profilePhoto: "https://i.pravatar.cc/150?img=4",
    studentName: "Sneha Joshi",
    studentId: "STU004",
    department: "Mechanical",
    course: "Diploma",
    email: "sneha@example.com",
    phoneNumber: "9876543213",
    address: "Satara",
    status: "Active",
  },
  {
    id: 5,
    profilePhoto: "https://i.pravatar.cc/150?img=5",
    studentName: "Rohan Deshmukh",
    studentId: "STU005",
    department: "Civil",
    course: "BTech",
    email: "rohan@example.com",
    phoneNumber: "9876543214",
    address: "Nagpur",
    status: "Active",
  },
  {
    id: 6,
    profilePhoto: "https://i.pravatar.cc/150?img=6",
    studentName: "Neha Kulkarni",
    studentId: "STU006",
    department: "Computer Science",
    course: "MCA",
    email: "neha@example.com",
    phoneNumber: "9876543215",
    address: "Nashik",
    status: "Inactive",
  },
  {
    id: 7,
    profilePhoto: "https://i.pravatar.cc/150?img=7",
    studentName: "Karan Singh",
    studentId: "STU007",
    department: "Information Technology",
    course: "BCA",
    email: "karan@example.com",
    phoneNumber: "9876543216",
    address: "Aurangabad",
    status: "Active",
  },
  {
    id: 8,
    profilePhoto: "https://i.pravatar.cc/150?img=8",
    studentName: "Anjali Patil",
    studentId: "STU008",
    department: "Computer Science",
    course: "BSc CS",
    email: "anjali@example.com",
    phoneNumber: "9876543217",
    address: "Solapur",
    status: "Active",
  },
  {
    id: 9,
    profilePhoto: "https://i.pravatar.cc/150?img=9",
    studentName: "Vikram Yadav",
    studentId: "STU009",
    department: "Electronics",
    course: "BTech",
    email: "vikram@example.com",
    phoneNumber: "9876543218",
    address: "Sangli",
    status: "Inactive",
  },
  {
    id: 10,
    profilePhoto: "https://i.pravatar.cc/150?img=10",
    studentName: "Pooja Shinde",
    studentId: "STU010",
    department: "Computer Science",
    course: "MCA",
    email: "pooja@example.com",
    phoneNumber: "9876543219",
    address: "Pimpri-Chinchwad",
    status: "Active",
  },
];

export default students;